# Generated by Django 5.2.7 on 2026-05-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('emoji', models.CharField(default='🔹', max_length=10)),
                ('gradient', models.CharField(default='from-blue-900/60 to-[#0B1120]', max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('github', models.URLField(blank=True)),
                ('demo', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
