# Generated by Django 5.2.7 on 2026-05-19 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='About me', max_length=100)),
                ('title_line1', models.CharField(default='Engineer. Developer.', max_length=100)),
                ('title_line2', models.CharField(default='Problem Solver.', max_length=100)),
                ('highlight_text', models.CharField(default='Problem Solver.', max_length=50)),
                ('profile_emoji', models.CharField(default='👨\u200d💻', max_length=10)),
                ('availability_badge', models.CharField(default='Available for hire', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'About Section',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_about_row')],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
                ('href', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Contact info',
                'ordering': ['order'],
                'unique_together': {('label', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='💼', max_length=10)),
                ('color', models.CharField(default='#2563EB', max_length=7)),
                ('bg_color', models.CharField(default='rgba(37,99,235,0.1)', max_length=20)),
                ('text_color', models.CharField(default='#93C5FD', max_length=7)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('role', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(default="👋 Hello, I'm", max_length=50)),
                ('name_line1', models.CharField(default='Isaac Michael', max_length=100)),
                ('name_line2', models.CharField(default='Ndoka', max_length=100)),
                ('highlight_text', models.CharField(default='Ndoka', max_length=50)),
                ('description', models.TextField(default='I build modern software systems...')),
                ('primary_cta', models.CharField(default='View Projects', max_length=50)),
                ('primary_cta_link', models.CharField(default='#projects', max_length=200)),
                ('secondary_cta', models.CharField(default='Contact Me', max_length=50)),
                ('secondary_cta_link', models.CharField(default='#contact', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Hero',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_hero_row')],
            },
        ),
        migrations.CreateModel(
            name='AboutParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='content.aboutsection')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('about_section', 'text')},
            },
        ),
        migrations.CreateModel(
            name='ExperienceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='content.experience')),
            ],
            options={
                'unique_together': {('experience', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content.aboutsection')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('about_section', 'label')},
            },
        ),
        migrations.CreateModel(
            name='TypedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typed_roles', to='content.hero')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('hero', 'role')},
            },
        ),
    ]
